# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitmux < Formula
  desc "Git in your tmux status bar."
  homepage "https://github.com/arl/gitmux"
  version "0.11.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/arl/gitmux/releases/download/v0.11.1/gitmux_v0.11.1_macOS_amd64.tar.gz"
      sha256 "36590bea6717a5791b369cc9ecb57e8fb147393b8ad18524978bee63cf3c636e"

      def install
        bin.install "gitmux"
      end
    end
    on_arm do
      url "https://github.com/arl/gitmux/releases/download/v0.11.1/gitmux_v0.11.1_macOS_arm64.tar.gz"
      sha256 "aec9b7183d528d6b76c1f48e0a0176bb352de7b0d36ea8a5b56962ce1b47c9a4"

      def install
        bin.install "gitmux"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/arl/gitmux/releases/download/v0.11.1/gitmux_v0.11.1_linux_amd64.tar.gz"
        sha256 "32b29a0627eb8abe68d29bc3a4f3a175870df8cc080dcf6ac888bd504a877f10"

        def install
          bin.install "gitmux"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/arl/gitmux/releases/download/v0.11.1/gitmux_v0.11.1_linux_arm64.tar.gz"
        sha256 "546cf8e6ae7a9879e6e49f83b7e831fc39eca2b29efac8c0151cc971efdb4248"

        def install
          bin.install "gitmux"
        end
      end
    end
  end
end
