# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitmux < Formula
  desc "Git in your tmux status bar."
  homepage "https://github.com/arl/gitmux"
  version "0.7.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arl/gitmux/releases/download/v0.7.11/gitmux_v0.7.11_macOS_amd64.tar.gz"
      sha256 "b9517808af18d7bbbe4ae79a2456ddce685f6f169f7c7312fe1a099b7cbaf9d8"

      def install
        bin.install "gitmux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arl/gitmux/releases/download/v0.7.11/gitmux_v0.7.11_macOS_arm64.tar.gz"
      sha256 "b5168a413934064561360b3185fd779d800d3b16d0db15f67955b822a74d2342"

      def install
        bin.install "gitmux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arl/gitmux/releases/download/v0.7.11/gitmux_v0.7.11_linux_arm64.tar.gz"
      sha256 "48253fb1ac848d4074bedfab3f4e127a17de8f650cfb280e2f8aef2a63f95b8c"

      def install
        bin.install "gitmux"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arl/gitmux/releases/download/v0.7.11/gitmux_v0.7.11_linux_amd64.tar.gz"
      sha256 "28946241984047bd1dea426e28106223b200050e7e559dbf9c2c4125e4339e3c"

      def install
        bin.install "gitmux"
      end
    end
  end
end
