# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitmux < Formula
  desc "Git in your tmux status bar."
  homepage "https://github.com/arl/gitmux"
  version "0.11.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arl/gitmux/releases/download/v0.11.5/gitmux_v0.11.5_macOS_amd64.tar.gz"
      sha256 "0ff0b4c4e30ca0615fc0cd966b7bc3f10b6c02b8a3164802b94e621aa5aee698"

      def install
        bin.install "gitmux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arl/gitmux/releases/download/v0.11.5/gitmux_v0.11.5_macOS_arm64.tar.gz"
      sha256 "89f0a88e1fbbd74d13dfbb92a5ccb2c3d5bc397546b8a4fb5372d98bacf79c0e"

      def install
        bin.install "gitmux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arl/gitmux/releases/download/v0.11.5/gitmux_v0.11.5_linux_amd64.tar.gz"
      sha256 "d46a10f5fe07ab5b8a902ac29c937e4d3c8d7f33ea30fa335d682601697b5a71"
      def install
        bin.install "gitmux"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arl/gitmux/releases/download/v0.11.5/gitmux_v0.11.5_linux_arm64.tar.gz"
      sha256 "89a03a76828267927d57904f0f716a9b9aad627d1697d5c0c883d60c09bb4ff6"
      def install
        bin.install "gitmux"
      end
    end
  end
end
