# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitmux < Formula
  desc "Git in your tmux status bar."
  homepage "https://github.com/arl/gitmux"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arl/gitmux/releases/download/v0.8.0/gitmux_v0.8.0_macOS_amd64.tar.gz"
      sha256 "9e69645943eb761fe8ce8e77191f1e54aea2027c4093b6f8cb3cab21ef9b487d"

      def install
        bin.install "gitmux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arl/gitmux/releases/download/v0.8.0/gitmux_v0.8.0_macOS_arm64.tar.gz"
      sha256 "aa118a76a4d1fc7b4c788ead7884ea592c5efb1a9b4ec809e38529bc6df08a6e"

      def install
        bin.install "gitmux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arl/gitmux/releases/download/v0.8.0/gitmux_v0.8.0_linux_arm64.tar.gz"
      sha256 "81a7844c15c747f1c292a55b920d80ff1cde92d0d55a05d74c04b29c839d1d2a"

      def install
        bin.install "gitmux"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arl/gitmux/releases/download/v0.8.0/gitmux_v0.8.0_linux_amd64.tar.gz"
      sha256 "c2b1a4b72e521ce6fd3ed039c3dcca2eaab88adead1fb5f6868f37aedcfe9543"

      def install
        bin.install "gitmux"
      end
    end
  end
end
