# This file was generated by GoReleaser. DO NOT EDIT.
cask "nestor" do
  name "nestor"
  desc "Nestor is a NES/Famicom emulator written in Go."
  homepage "https://github.com/arl/nestor"
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nestor"

  on_macos do
    on_arm do
      url "https://github.com/arl/nestor/releases/download/v#{version}/nestor_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/arl/nestor"
      sha256 "f4b4284912bce2f0758287fc45a2b9193a77f0d14b03f704a2ef377f9d496fbc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nestor"]
    end
  end

  # No zap stanza required
end
