# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Nestor < Formula
  desc ":space_invader: nes/famicom emulator"
  homepage "https://github.com/arl/nestor"
  url "https://github.com/arl/nestor/archive/refs/tags/v0.6.0.tar.gz"
  sha256 "748a8a9eecd23ee4502fdbd6d9b346e82731a2f359c34df44b416eef70ee0fde"
  license "GPL-3.0"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install "nestor"
  end
end
