# This file was generated by GoReleaser. DO NOT EDIT.
cask "nestor" do
  name "nestor"
  desc "Nestor is a NES/Famicom emulator written in Go."
  homepage "https://github.com/arl/nestor"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nestor"

  on_macos do
    on_arm do
      url "https://github.com/arl/nestor/releases/download/v#{version}/nestor_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/arl/nestor"
      sha256 "8691638b7f37a2aa003f33a0e58119271ebbd16ecc6329d5328a6db725b8861d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nestor"]
    end
  end

  # No zap stanza required
end
